// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: server_data.proto
// Protobuf C++ Version: 5.29.5

#include "server_data.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace myproject {

inline constexpr EmptyMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : placeholder_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EmptyMessage::EmptyMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EmptyMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyMessageDefaultTypeInternal() {}
  union {
    EmptyMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyMessageDefaultTypeInternal _EmptyMessage_default_instance_;
}  // namespace myproject
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_server_5fdata_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_server_5fdata_2eproto = nullptr;
const ::uint32_t
    TableStruct_server_5fdata_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::myproject::EmptyMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::myproject::EmptyMessage, _impl_.placeholder_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::myproject::EmptyMessage)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::myproject::_EmptyMessage_default_instance_._instance,
};
const char descriptor_table_protodef_server_5fdata_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021server_data.proto\022\tmyproject\"#\n\014EmptyM"
    "essage\022\023\n\013placeholder\030\001 \001(\005b\006proto3"
};
static ::absl::once_flag descriptor_table_server_5fdata_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_server_5fdata_2eproto = {
    false,
    false,
    75,
    descriptor_table_protodef_server_5fdata_2eproto,
    "server_data.proto",
    &descriptor_table_server_5fdata_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_server_5fdata_2eproto::offsets,
    file_level_enum_descriptors_server_5fdata_2eproto,
    file_level_service_descriptors_server_5fdata_2eproto,
};
namespace myproject {
// ===================================================================

class EmptyMessage::_Internal {
 public:
};

EmptyMessage::EmptyMessage(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:myproject.EmptyMessage)
}
EmptyMessage::EmptyMessage(
    ::google::protobuf::Arena* arena, const EmptyMessage& from)
    : EmptyMessage(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE EmptyMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void EmptyMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.placeholder_ = {};
}
EmptyMessage::~EmptyMessage() {
  // @@protoc_insertion_point(destructor:myproject.EmptyMessage)
  SharedDtor(*this);
}
inline void EmptyMessage::SharedDtor(MessageLite& self) {
  EmptyMessage& this_ = static_cast<EmptyMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* EmptyMessage::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EmptyMessage(arena);
}
constexpr auto EmptyMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EmptyMessage),
                                            alignof(EmptyMessage));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EmptyMessage::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EmptyMessage_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EmptyMessage::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EmptyMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EmptyMessage::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EmptyMessage>(), &EmptyMessage::ByteSizeLong,
            &EmptyMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EmptyMessage, _impl_._cached_size_),
        false,
    },
    &EmptyMessage::kDescriptorMethods,
    &descriptor_table_server_5fdata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EmptyMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> EmptyMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::myproject::EmptyMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 placeholder = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EmptyMessage, _impl_.placeholder_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(EmptyMessage, _impl_.placeholder_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 placeholder = 1;
    {PROTOBUF_FIELD_OFFSET(EmptyMessage, _impl_.placeholder_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void EmptyMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:myproject.EmptyMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.placeholder_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EmptyMessage::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EmptyMessage& this_ = static_cast<const EmptyMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EmptyMessage::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EmptyMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:myproject.EmptyMessage)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 placeholder = 1;
          if (this_._internal_placeholder() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_placeholder(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:myproject.EmptyMessage)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EmptyMessage::ByteSizeLong(const MessageLite& base) {
          const EmptyMessage& this_ = static_cast<const EmptyMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EmptyMessage::ByteSizeLong() const {
          const EmptyMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:myproject.EmptyMessage)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 placeholder = 1;
            if (this_._internal_placeholder() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_placeholder());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EmptyMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EmptyMessage*>(&to_msg);
  auto& from = static_cast<const EmptyMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:myproject.EmptyMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_placeholder() != 0) {
    _this->_impl_.placeholder_ = from._impl_.placeholder_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EmptyMessage::CopyFrom(const EmptyMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:myproject.EmptyMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EmptyMessage::InternalSwap(EmptyMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.placeholder_, other->_impl_.placeholder_);
}

::google::protobuf::Metadata EmptyMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace myproject
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_server_5fdata_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
